version: '3'
services:
  sysadmin-web-app-back:
    image: matoferreira/sysadmin-web-app-back
    ports:
      - "3000:3000"
    networks:
      - sysadmin-network

  sysadmin-web-app:
    image: matoferreira/sysadmin-web-app
    ports:
      - "80:80"
    networks:
      - sysadmin-network

networks:
  sysadmin-network:
    driver: bridge
