# Use an official Nginx image as a parent image
FROM nginx:alpine

# Copy the local files into the container at the working directory
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
